@host = http://localhost:5001
@cloud = https://app-clo25-claes.azurewebsites.net

### Root - returns a small JSON object
GET {{host}}/

### Health - should always return 200 OK
GET {{host}}/health

### Info - which machine answered
GET {{host}}/info

### Cloud root - same app, different machine
GET {{cloud}}/

### Cloud health - should always return 200 OK
GET {{cloud}}/health
